name: Build and Release Extension

on:
  push:
    branches:
      - main
    paths:
      - 'manifest.json'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version_check.outputs.new_version }}
      release_exists: ${{ steps.check_release.outputs.release_exists }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get current version from manifest.json
        id: version_check
        run: |
          # Get current version from manifest.json
          CURR_VERSION=$(jq -r '.version' manifest.json)
          echo "Current version: $CURR_VERSION"
          echo "new_version=$CURR_VERSION" >> $GITHUB_OUTPUT

      - name: Check if release already exists
        id: check_release
        run: |
          VERSION="${{ steps.version_check.outputs.new_version }}"
          if gh release view "v$VERSION" >/dev/null 2>&1; then
            echo "Release v$VERSION already exists"
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Release v$VERSION does not exist"
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-release:
    needs: check-version
    if: needs.check-version.outputs.release_exists == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Create CRX file
        run: |
          VERSION="${{ needs.check-version.outputs.new_version }}"
          
          echo "${{ secrets.EXTENSION_KEY }}" > extension-key.pem
          
          # Install crx3 for creating CRX files
          npm install -g crx3
          
          # Create CRX file from the dist directory
          crx3 dist "packed/reNorsk-v$VERSION.crx"
          
          echo "Created: reNorsk-v$VERSION.crx"

      - name: Generate changelog
        id: changelog
        run: |
          VERSION="${{ needs.check-version.outputs.new_version }}"
          PREV_VERSION="${{ needs.check-version.outputs.previous_version }}"
          
          echo "## Changes in v$VERSION" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          
          # Get commits since last version tag (if it exists)
          if git tag | grep -q "v$PREV_VERSION"; then
            echo "### Commits since v$PREV_VERSION:" >> CHANGELOG.md
            git log --oneline "v$PREV_VERSION"..HEAD --grep="^(?!Merge)" >> CHANGELOG.md 2>/dev/null || true
          else
            echo "### Recent commits:" >> CHANGELOG.md
            git log --oneline -10 >> CHANGELOG.md
          fi
          
          echo "" >> CHANGELOG.md
          echo "### Installation" >> CHANGELOG.md
          echo "- Download the \`reNorsk-v$VERSION.zip\` file for manual installation" >> CHANGELOG.md
          echo "- Or download the \`reNorsk-v$VERSION.crx\` file for direct installation (may require developer mode)" >> CHANGELOG.md

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.check-version.outputs.new_version }}"
          name: "reNorsk v${{ needs.check-version.outputs.new_version }}"
          body_path: "CHANGELOG.md"
          draft: false
          prerelease: false
          files: |
            packed/reNorsk-v${{ needs.check-version.outputs.new_version }}.zip
            packed/reNorsk-v${{ needs.check-version.outputs.new_version }}.crx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          VERSION="${{ needs.check-version.outputs.new_version }}"
          echo "🎉 Successfully created release v$VERSION"
          echo "📦 Assets created:"
          ls -la packed/
          echo ""
          echo "🔗 Release URL: ${{ steps.create_release.outputs.html_url }}"
